FROM python:3.13-slim
ARG timezone=Asia/Bangkok
ENV TZ $timezone
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg2 \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*
RUN wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add -
RUN echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    temurin-21-jdk \
    python3-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/Nepumi-Jr/Garedami.git ./Garedami
COPY ./grader/template ./Garedami/
COPY ./grader/grader.py .
COPY ./grader/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "grader.py"]